name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B clean package source:jar javadoc:jar
          echo "Built files in target:"
          ls -la core/target/

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Extract Changelog
        id: extract_changelog
        run: |
          # Extract the section for current version from CHANGELOG.md
          VERSION=${{ env.VERSION }}
          # Remove 'v' prefix if present in version
          VERSION=${VERSION#v}
          # Extract changelog section
          CHANGELOG_SECTION=$(awk -v ver="$VERSION" '
            /^## \[.*\]/ { if (p) { exit }; if ($0 ~ ver) { p=1; print; next } }
            p { print }
          ' CHANGELOG.md)
          # Escape newlines and set output
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_SECTION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
          body: |
            Flow DSL ${{ github.ref }} Release
            
            ## Changelog
            ${{ env.CHANGELOG }}
            
            For full documentation, please refer to [README.md](README.md).

      - name: Upload Main JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./core/target/flow-dsl-core-${{ env.VERSION }}.jar
          asset_name: flow-dsl-core-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive

      - name: Upload Sources JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./core/target/flow-dsl-core-${{ env.VERSION }}-sources.jar
          asset_name: flow-dsl-core-${{ env.VERSION }}-sources.jar
          asset_content_type: application/java-archive

      - name: Upload JavaDoc JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./core/target/flow-dsl-core-${{ env.VERSION }}-javadoc.jar
          asset_name: flow-dsl-core-${{ env.VERSION }}-javadoc.jar
          asset_content_type: application/java-archive 